import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/root/Provider";
import Footer from "@/components/root/Footer";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/root/Header";
import { getAllParentServices } from "@/lib/fetchServices";

const bodyFont = Inter({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-body",
});

const headingFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700", "500","300"],
  variable: "--font-heading",
});

// const monoFont = JetBrains_Mono({
//   subsets: ["latin"],
//   variable: "--font-mono",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const { serviceCard } = await getAllParentServices();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body
  className={`${headingFont.variable} ${bodyFont.variable} antialiased bg-[#F9FAFB] relative overflow-x-hidden`}
>
      <Header services={serviceCard} />
        <Provider>
          <main className="max-w-full">{children}</main>
          <Toaster />
        </Provider>

        <footer className="bg-[#0E052A] flex items-center justify-center ">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
