import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Provider from "@/components/root/Provider";
import Nav from "@/components/root/Nav";
import Footer from "@/components/root/Footer";

const bodyFont = Inter({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-body",
});

const headingFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700", "500"],
  variable: "--font-heading",
});

// const monoFont = JetBrains_Mono({
//   subsets: ["latin"],
//   variable: "--font-mono",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${headingFont.variable} ${bodyFont.variable} antialiased bg-[#F9FAFB] relative w-screen overflow-x-hidden`}
      >
        <header className="fixed  left-0  px-22 w-full top-6  z-50   flex items-center justify-center">
          <Nav />
        </header>
        <Provider>
          <main className="max-w-full">{children}</main>
        </Provider>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
